# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unboundcli < Formula
  desc "CLI for syncing with UNBOUND DNS on OPNSENSE router"
  homepage "https://github.com/jeeftor/unboundCLI"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/jeeftor/unboundCLI/releases/download/v0.0.1/unboundCLI_0.0.1_Darwin_all.tar.gz"
    sha256 "25a92e7341eeee16d09244c76f6e9aff45456cf5db5addad1cac0288e2ff6e9f"

    def install
      bin.install "unboundCLI"
      bash_completion.install "completions/bash/unboundCLI" => "unboundcli"
      zsh_completion.install "completions/zsh/unboundCLI" => "_unboundcli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jeeftor/unboundCLI/releases/download/v0.0.1/unboundCLI_0.0.1_Linux_x86_64.tar.gz"
      sha256 "a0922dd457790fe8183aea4829bc602cf0a75f452a826a51d7edf669847831b0"
      def install
        bin.install "unboundCLI"
        bash_completion.install "completions/bash/unboundCLI" => "unboundcli"
        zsh_completion.install "completions/zsh/unboundCLI" => "_unboundcli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jeeftor/unboundCLI/releases/download/v0.0.1/unboundCLI_0.0.1_Linux_arm64.tar.gz"
      sha256 "d1d7d86e0336a34a5aa6c0ceea1049ae4a464f00bda2f32cb3278dfa96406af4"
      def install
        bin.install "unboundCLI"
        bash_completion.install "completions/bash/unboundCLI" => "unboundcli"
        zsh_completion.install "completions/zsh/unboundCLI" => "_unboundcli"
      end
    end
  end

  test do
    system "#{bin}/unboundCLI", "--version"
  end
end
