# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AudiobookOrganizer < Formula
  desc "License Manager Tool"
  homepage "https://github.com/jeeftor/license-manager"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.4/audiobook-organizer_Darwin_x86_64.tar.gz"
      sha256 "ff5bf44dc0e95e7e3de90ba983e654d5afcb6e758f1b87f9b9bf9865345743ab"

      def install
        bin.install "audiobook-organizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.4/audiobook-organizer_Darwin_arm64.tar.gz"
      sha256 "a1704d0572286803e88875cb27834e9c1257f99db144d12f2172c60d92194567"

      def install
        bin.install "audiobook-organizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.4/audiobook-organizer_Linux_x86_64.tar.gz"
        sha256 "eca33648870faef3b3389bdafff5aa7fc103beabef7bb2e0c907a62d1169dd1e"

        def install
          bin.install "audiobook-organizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.4/audiobook-organizer_Linux_arm64.tar.gz"
        sha256 "a9807f466052fe91be05462599841e05138c5e9f922db7f4f1ccfc1675edb061"

        def install
          bin.install "audiobook-organizer"
        end
      end
    end
  end

  test do
    system "#{bin}/audiobook-organizer --version"
  end
end
