# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AudiobookOrganizer < Formula
  desc "License Manager Tool"
  homepage "https://github.com/jeeftor/license-manager"
  version "0.9.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.7/audiobook-organizer_Darwin_x86_64.tar.gz"
      sha256 "363caee1f23d58c7c6fe861ab652b31e6bbdec4a0f33b2302d8405ea0fe39551"

      def install
        bin.install "audiobook-organizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.7/audiobook-organizer_Darwin_arm64.tar.gz"
      sha256 "99a80d2703cec525615a300bf0fabf7d713222e6d7f5d5063e522f68f6686c8c"

      def install
        bin.install "audiobook-organizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.7/audiobook-organizer_Linux_x86_64.tar.gz"
        sha256 "d51f0217a7038ba2b6e3db9bd5265c65ce2b3b935203037af7260d520266bef8"

        def install
          bin.install "audiobook-organizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/audiobook-organizer/releases/download/v0.9.7/audiobook-organizer_Linux_arm64.tar.gz"
        sha256 "731faa86907fd479e70471edfb623978c3763bdbe80340d25d8bf2b3233e8e94"

        def install
          bin.install "audiobook-organizer"
        end
      end
    end
  end

  test do
    system "#{bin}/audiobook-organizer --version"
  end
end
