# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LicenseManager < Formula
  desc "License Manager Tool"
  homepage "https://github.com/jeeftor/license-manager"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeeftor/license-manager/releases/download/v0.0.3/license-manager_Darwin_x86_64.tar.gz"
      sha256 "2c32d2f45233a9bfc2a6e4a5da179d8e7d5adcccecd2601132a06f9d648280af"

      def install
        bin.install "license-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeeftor/license-manager/releases/download/v0.0.3/license-manager_Darwin_arm64.tar.gz"
      sha256 "5cbeee23328d0c87f68954184958d89517456f051a1908f13081be2b0fe69b43"

      def install
        bin.install "license-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/license-manager/releases/download/v0.0.3/license-manager_Linux_x86_64.tar.gz"
        sha256 "175368d372f8faf27be428e99ba141d30509f0082c37b4b7ed1572bde82b1b4b"

        def install
          bin.install "license-manager"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/license-manager/releases/download/v0.0.3/license-manager_Linux_arm64.tar.gz"
        sha256 "eff4596b2a3ee39dce89168a3a24b192a6ed3bf2162322585a253946b80e81ef"

        def install
          bin.install "license-manager"
        end
      end
    end
  end

  test do
    system "#{bin}/license-manager --version"
  end
end
