# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LicenseManager < Formula
  desc "License Manager Tool"
  homepage "https://github.com/jeeftor/license-manager"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeeftor/license-manager/releases/download/v0.0.4/license-manager_Darwin_x86_64.tar.gz"
      sha256 "648150071bf021e02ee4d6dddb466963a9d99a1d94f4b99c7bfb20ab9903b6d7"

      def install
        bin.install "license-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeeftor/license-manager/releases/download/v0.0.4/license-manager_Darwin_arm64.tar.gz"
      sha256 "583d448c98e00ee794f934daca25209acdba6d2da94c74ecc1cee177bb733318"

      def install
        bin.install "license-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/license-manager/releases/download/v0.0.4/license-manager_Linux_x86_64.tar.gz"
        sha256 "8095c8cd37f32d21e1be92562db83887a161d7a9ab053d0394a052216ac4b7fe"

        def install
          bin.install "license-manager"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jeeftor/license-manager/releases/download/v0.0.4/license-manager_Linux_arm64.tar.gz"
        sha256 "b4149e7d605ed4790767948189dc5986eda5ce31e240aa1bc9b7cd2d41c6e5d1"

        def install
          bin.install "license-manager"
        end
      end
    end
  end

  test do
    system "#{bin}/license-manager --version"
  end
end
